# Generated by Django 3.2 on 2023-09-13 12:14

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('super-admin', 'super-admin'), ('sttuf', 'stuff'), ('customer', 'customer')], max_length=50, verbose_name='type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Image')),
                ('code', models.CharField(default=User.models.generator, max_length=8, verbose_name='code')),
                ('code_used', models.BooleanField(default=False, verbose_name='Code Used')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
        ),
    ]
