# Generated by Django 3.2 on 2023-09-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
